'use client';
import { useRef, useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { ArrowRight, BarChart3, Bell, CalendarDays, Check, CheckCircle2, ChevronDown, CircleHelp, ClipboardList, Cloud, Code2, ExternalLink, FileCheck2, FileText, Headphones, Info, LayoutGrid, Menu, Monitor, PanelsTopLeft, RefreshCw, Rocket, Save, Settings, ShieldCheck, Trash2, UploadCloud, X } from 'lucide-react';

const steps = ['BRD Intake & Registration','Requirement Normalisation','Layout & Component Recommendation','GX1 Screen Specification','Prototype (Penpot)','Front-End Code Generation','QA, Evidence & Approval','Release & Deployment'];
const nav = [['intake','BRD Intake'],['check','Intake & Registration'],['refresh','Requirement Normalisation'],['quality','BRD Quality Check'],['history','Intake History'],['requirements','Requirements'],['layout','Layout & Components'],['screen','Screen Specification'],['prototype','Prototypes'],['code','Code Generation'],['qa','QA & Evidence'],['release','Releases']];
const schema = z.object({ title:z.string().min(1,'BRD title is required'), description:z.string().min(1,'Short description is required'), notes:z.string(), assignee:z.string().min(1) });
type FormData=z.infer<typeof schema>;
const iconSet = { info:Info, refresh:RefreshCw, upload:UploadCloud, check:CheckCircle2, trash:Trash2, bell:Bell, help:CircleHelp, menu:Menu, ext:ExternalLink, cal:CalendarDays, save:Save, document:FileCheck2, cloud:Cloud, support:Headphones, arrow:ArrowRight, close:X };
function I({n}:{n:keyof typeof iconSet}) { const Icon=iconSet[n]; return <Icon className={'ico '+n} aria-hidden="true" strokeWidth={1.7}/> }
const navSet: Record<string, React.ElementType> = { intake:FileText, check:Check, refresh:RefreshCw, quality:ClipboardList, history:BarChart3, requirements:ClipboardList, layout:LayoutGrid, screen:Monitor, prototype:PanelsTopLeft, code:Code2, qa:ShieldCheck, release:Rocket };
function NavIcon({name}:{name:string}) { const Icon=navSet[name] ?? FileText; return <Icon className="nav-ico" size={18} strokeWidth={1.65}/> }
function Label({children,required}:{children:React.ReactNode,required?:boolean}) { return <label>{children}{required && <b className="required"> *</b>}</label> }
function Section({title,children,className=''}:{title:React.ReactNode,children:React.ReactNode,className?:string}) {
 const projectTitle = typeof title === 'string' && title.includes('<small>');
 const isOptional = typeof title === 'string' && title.includes('(Optional)');
 const visibleTitle = typeof title === 'string' ? title.replace(/\s*<small>.*?<\/small>/, '') : title;
 return <section className={'form-card section '+className}><h3>{projectTitle ? <>{visibleTitle} <small>{isOptional ? '(Optional)' : '(From GSolve)'}</small></> : title}</h3>{children}</section>
}
function Meta({label,value}:{label:string,value:string}) { return <div className="meta"><span>{label}</span><strong>{value}</strong></div> }

export default function Home(){
 const {register,handleSubmit,watch,formState:{errors}}=useForm<FormData>({defaultValues:{title:'Daily Task Management System',description:'System to manage daily tasks, assignments, tracking and approvals.',notes:'This is part of GSolve pilot phase 1.',assignee:'UX-CX Lead (Jahir Hussain)'}});
 const [reviewers,setReviewers]=useState(['AI Architect (Zain Israr)','System Architect']); const [tags,setTags]=useState(['Task Management','Operations','GSolve Pilot']); const [tag,setTag]=useState(''); const [file,setFile]=useState('Daily_Task_Management_BRD_v1.0.pdf'); const [message,setMessage]=useState(''); const [activeStep,setActiveStep]=useState(0); const [activeNav,setActiveNav]=useState(0); const input=useRef<HTMLInputElement>(null);
 const addTag=(e:React.KeyboardEvent<HTMLInputElement>)=>{if(e.key==='Enter'){e.preventDefault();const x=tag.trim();if(x&&!tags.some(t=>t.toLowerCase()===x.toLowerCase()))setTags([...tags,x]);setTag('')}};
 const choose=(f?:File)=>{if(!f)return;if(f.size>50*1024*1024||!/(pdf|vnd.openxmlformats-officedocument.wordprocessingml.document)$/.test(f.type))setMessage('Please choose a PDF or DOCX file under 50 MB.');else {setFile(f.name);setMessage('Document attached successfully.')}};
 const submit=(kind:string)=>handleSubmit((data)=>{const check=schema.safeParse(data);setMessage(check.success?`${kind} saved successfully.`:'Please complete all required fields.');})()
 return <div className="shell">
  <aside className="sidebar"><div className="brand"><button className="hamb" aria-label="Open navigation"><I n="menu"/></button><div><div className="logo">GX1</div><small>Platform</small></div></div><div className="nav-scroll"><p className="group">BRD PIPELINE <ChevronDown size={14}/></p>{nav.map(([i,name],x)=><div key={name} role="button" tabIndex={0} onClick={()=>setActiveNav(x)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setActiveNav(x)}}} className={'nav '+(x===activeNav?'active ':'')+(x===1?'sub selected ':'') }><NavIcon name={i}/><span className="nav-label">{name}</span>{[0,5,6,7,8,9,10,11].includes(x)&&<ChevronDown className="nav-chevron" size={14}/>}</div>)}<div className="admin"><p className="group">ADMINISTRATION</p><div className="nav"><Settings className="nav-ico" size={18}/><span className="nav-label">Admin</span><ChevronDown className="nav-chevron" size={14}/></div><div className="nav"><BarChart3 className="nav-ico" size={18}/><span className="nav-label">Reports</span><ChevronDown className="nav-chevron" size={14}/></div></div></div><div className="side-bottom"><div className="context"><b>Project Context (GSolve)</b><span>GSOLVE-PILOT-001 <I n="ext"/></span></div><div className="profile"><div className="avatar">RS</div><div><b>Rohit Sharma</b><small>Business Analyst</small></div><ChevronDown size={14}/></div></div></aside>
  <main className="app"><header><div><h1>GX1 – BRD to Production Platform</h1><p>From BRD Intake to Production-Ready Front-End &amp; Evidence</p></div><div className="head-right"><span className="bell"><I n="bell"/><b>12</b></span><I n="help"/><div className="avatar large">RS</div><div><strong>Rohit Sharma</strong><small>Business Analyst</small></div><span>⌄</span></div></header>
   <div className="body"><nav className="stepper" aria-label="Workflow steps">{steps.map((s,i)=><div role="button" tabIndex={0} aria-current={i===activeStep?'step':undefined} onClick={()=>setActiveStep(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setActiveStep(i)}}} className={'step '+(i===activeStep?'current':'')} key={s}><span>{i+1}</span><b>{s}</b>{i<7&&<i>→</i>}</div>)}</nav>
   <div className="content"><div className="workspace"><div className="title"><h2>BRD Intake &amp; Registration</h2><p>Capture and register a new Business Requirement Document (BRD) against a GSolve project.</p></div><div className="notice"><I n="info"/> Project details and metadata are pulled from GSolve and cannot be edited here.</div>
    <Section title="1. &nbsp; PROJECT SELECTION  <small>(From GSolve)</small>" className="project"><button className="refresh" onClick={()=>{setMessage('Refreshing project data…');setTimeout(()=>setMessage('Project details refreshed from GSolve.'),700)}}><I n="refresh"/> Refresh from GSolve</button><Label required>Select GSolve Project</Label><select defaultValue="pilot"><option value="pilot">GSOLVE-PILOT-001 &nbsp; | &nbsp; GSolve Pilot Implementation</option></select><div className="summary"><div className="project-icon"><FileText size={18}/></div><Meta label="Project Code" value="GSOLVE-PILOT-001"/><Meta label="Project Name" value="GSolve Pilot Implementation"/><Meta label="Client" value="GREEN Limited"/><Meta label="Project Manager" value="Jahir Hussain"/><div className="meta"><span>Status</span><strong className="status">Active</strong></div></div><p className="metadata-title">Project Metadata (Read-only from GSolve)</p><div className="metadata">{[['Start Date','01 May 2026'],['Target End Date','31 Dec 2026'],['Currency','PGK'],['Project Type','Internal Development'],['Business Domain','Operations'],['Sub Domain','Task Management'],['Contract Reference','N/A'],['Budget (PGK)','250,000.00'],['Project Priority','High'],['Project Stage','Planning'],['Last Updated','20 Jul 2026 09:30 AM'],['Updated By','System (GSolve)']].map(([l,v])=><Meta key={l} label={l} value={v}/>)}</div></Section>
    <form onSubmit={e=>{e.preventDefault();submit('BRD')}} className="form-grid"><Section title="2. &nbsp; BRD INFORMATION"><Label required>BRD Title</Label><input {...register('title')} aria-invalid={!!errors.title}/><Label required>Short Description</Label><div className="counter-wrap"><textarea {...register('description')} maxLength={500}/><small>{watch('description').length} / 500</small></div></Section><Section title="3. &nbsp; DOCUMENT UPLOAD"><Label required>Upload BRD Document (PDF/DOCX)</Label><div className="drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files[0])}} onClick={()=>input.current?.click()}><I n="upload"/><b>Drag &amp; drop file here</b><span>or click to browse</span><input ref={input} type="file" accept=".pdf,.docx" onChange={e=>choose(e.target.files?.[0])}/></div>{file&&<div className="file"><span className="pdf">PDF</span><div><b>{file}</b><small>2.4 MB</small></div><I n="check"/><button aria-label="Remove file" onClick={()=>setFile('')}><I n="trash"/></button></div>}<p className="upload-note">Max file size: 50 MB <i/> Accepted formats: PDF, DOCX</p></Section>
     <Section title="4. &nbsp; CLASSIFICATION"><div className="two"><div><Label>Business Domain</Label><select defaultValue="Operations"><option>Operations</option></select></div><div><Label>Sub Domain</Label><select defaultValue="Task Management"><option>Task Management</option></select></div></div><div className="three"><div><Label required>Complexity</Label><select><option>Medium</option></select></div><div><Label required>Project Type</Label><select><option>Internal Development</option></select></div><div><Label required>Regulatory Impact</Label><select><option>Low</option></select></div></div></Section><Section title="5. &nbsp; ASSIGNMENT"><Label required>Assign To</Label><select {...register('assignee')}><option>UX-CX Lead (Jahir Hussain)</option></select><Label required>Reviewers</Label><div className="tag-select">{reviewers.map(r=><span key={r}>{r}<button type="button" onClick={()=>setReviewers(reviewers.filter(x=>x!==r))}>×</button></span>)}<b>⌄</b></div></Section>
     <Section title="6. &nbsp; PRIORITY &amp; TARGET"><div className="two"><div><Label>Priority</Label><select><option>🔴 &nbsp; High</option></select></div><div><Label>Target Release Date</Label><div className="date"><input defaultValue="30/09/2026"/><I n="cal"/></div></div></div></Section><Section title="7. &nbsp; TAGS &amp; NOTES <small>(Optional)</small>"><div className="two tag-notes"><div><Label>Tags</Label><div className="tag-input">{tags.map(t=><span key={t}>{t}<button type="button" onClick={()=>setTags(tags.filter(x=>x!==t))}>×</button></span>)}<input value={tag} onChange={e=>setTag(e.target.value)} onKeyDown={addTag} placeholder="Type and press Enter"/></div></div><div><Label>Notes</Label><div className="counter-wrap"><textarea {...register('notes')} maxLength={500}/><small>{watch('notes').length} / 500</small></div></div></div></Section></form>
   </div><aside className="rail"><div className="rail-card document"><div><span>Screen No.</span><b>GX1-S1</b></div><div><span>Asset / Artefact No.</span><b>GX1-BRD-INTAKE-001</b></div><div><span>Workflow Step</span><b>1 of 8</b></div><div><span>Version</span><b>1.0</b></div><div><span>Date</span><b>20 Jul 2026</b></div></div><Rail title="INPUT FIELDS CHECKLIST" rows={['Project Selection (From GSolve)','BRD Title','Document Upload','Classification','Assignment','Priority & Target']}/><Rail title="SYSTEM ACTIONS" rows={['Project details pulled from GSolve','BRD will be created with unique BRD ID','Metadata is auto-saved','Intake status set to “Draft” or “Submitted”','Notification sent to assigned team']} squared/><div className="rail-card help"><h3>HELP &amp; GUIDANCE</h3>{['How BRD intake works','BRD writing best practices','Classification guidelines','GSolve integration reference'].map(x=><p key={x}>• &nbsp;{x}<I n="ext"/></p>)}<button>♧ &nbsp; Contact Support</button></div></aside></div></div>
  <footer><span>GX1 Platform <i/> Confidential – Internal Use Only</span><b>Classification: Internal &amp; Confidential</b><div><button onClick={()=>submit('Draft')}><I n="save"/> Save as Draft</button><button className="submit" onClick={()=>submit('BRD')}>Submit for Processing &nbsp; →</button></div><span>© GREEN Limited 2026. All rights reserved.</span></footer>{message&&<div role="status" className="toast">{message}<button onClick={()=>setMessage('')}>×</button></div>}</main></div>
}
function Rail({title,rows,squared=false}:{title:string,rows:string[],squared?:boolean}){return <div className="rail-card"><h3>{title}</h3>{rows.map(x=><p key={x}><I n={squared?'document':'check'}/>{x}</p>)}</div>}
